language: python

python:
  - "3.6"

install:
  - pip install coverage pytest pytest-cov codecov numpy scipy matplotlib tensorflow pandas
  - pip install --no-deps .  # Test installation correctness

script:
  - py.test -vv  # Test against installed code

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall tf_G -y
  - pip install --no-deps -e .
  - py.test --cov
  - codecov
